### ISSUE TITLE
setup.py: Issue with the `parse_version` function

### ISSUE THREAD

**Issue by KennethCho-CKH** [Kitware/kwcoco#4]
There is one issue with the code, the `parse_version` function relies on a `static_parse` function to extract the value of the `__version__` constant from a Python file. However, the `static_parse` function is not designed to handle all possible cases, and it may not work as expected for certain source files. For example, if the constant is defined using an expression instead of a string literal, or if it is defined in a way that is not immediately obvious to the static parser, the function may fail to extract the correct value or raise an exception. This could lead to incorrect or inconsistent version numbers being used during the installation or distribution of the package. It may be necessary to implement additional error handling or fallback mechanisms to ensure that the version number is always correctly identified and used.

**Comment by Erotemic** [comment]
Well, it's partially correct, it does fail if it's not a constant! However what this next gen spamer overlooks is that the `__init__.py` is a great place for the "one source of truth" about the module version. Furthermore I don't see a way for it to cause an issue at install time. Maybe it can train on that and get a little better at Python design in the meantime. :fire:

**Comment by Erotemic** [comment]
@andygeorge Thanks for the heads up. Spammed by AI is a weird experience. But I suppose this is just the beginning. I'm curious who you are and how you ended up in this thread? Are you warning people about the bot, or are you a kwcoco user?

**Comment by KennethCho-CKH** [comment]
> @andygeorge Thanks for the heads up. Spammed by AI is a weird experience. But I suppose this is just the beginning. I'm curious who you are and how you ended up in this thread? Are you warning people about the bot, or are you a kwcoco user?

I'm not an AI, I'm just a junior programmer trying to learn programming with ChatGPT, I don't know who that guy is, but he is targeting me everywhere and spamming my email inbox, I reported him anyway.

**Comment by Erotemic** [comment]
Oh, this is fun. 
![image](https://user-images.githubusercontent.com/3186211/230437472-05d864a6-7207-47eb-bf62-12eb3693836f.png)

Who wants to take a turning test?

In any case @KennethCho-CKH if you are a person, are you actually experiencing a problem? Are you a user of kwcoco? If you are a junior programmer you should become familiar with the concept of [single source of truth](https://en.wikipedia.org/wiki/Single_source_of_truth).
